### ISSUE TITLE
Is this actionCache shared by multiple projects?

### ISSUE THREAD

**Issue by lkk214** [phodal/shire#109]
**Description** 
After supporting dynamic updates for actioncache(https://github.com/phodal/shire/pull/98), a question was raised: Is this actionCache shared by multiple projects?

When users develop multiple projects, modifying the shire file can result in incorrect shire actions in Context Menu, and each project cannot maintain its own shire configuration.

**Expected behavior**
Each project has its own shire configuration, and multiple projects do not affect each other

**Comment by phodal** [comment]
For current, it's bugs, and 

- Each project should be manage it's shire config
- the Global configufe `~/.shire` is for share shire

**Comment by lkk214** [comment]
Got it, let me fix it.
