### ISSUE TITLE
Shire Skecth: A Multi-file viewer, render and edit

### ISSUE THREAD

**Issue by phodal** [phodal/shire#153]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### Diff Sketch

- Inlay Diff
- Apply, Revert Menu (`AllIcons.Actions.Rollback`), Cancel (`AllIcons.Vcs.Abort`)

<img width="1408" alt="图片" src="https://github.com/user-attachments/assets/34196d66-3593-4463-b943-6e10af8d04fd">

IDEA Apis:

```xml
<action id="Vcs.RollbackChangedLines" class="com.intellij.openapi.vcs.ex.RollbackLineStatusAction" icon="AllIcons.Actions.Rollback"/>
<action id="Vcs.ShowDiffChangedLines" class="com.intellij.openapi.vcs.ex.ShowDiffLineStatusAction" icon="AllIcons.Actions.Diff"/>
```

UI: `TwosideContentPanel` with: `SimpleDiffViewer`

### Mermaid Sketch

https://plugins.jetbrains.com/plugin/20146-mermaid

### PlantUML Sketch

https://plugins.jetbrains.com/plugin/7017-plantuml-integration

### Error Handling (TBC)

- Goto symbol: `/goto`
- Compile output with HyperLink => AutoParse

Compile output:

```bash
Prepare for running goto-symbol.shire...
Shire Script: /Users/phodal/IdeaProjects/shire-demo/.shire/command/goto-symbol.shire
Shire Script Compile output:
/Users/phodal/IdeaProjects/shire-demo/src/main/java/com/phodal/shire/demo/controller/AdvertiseController.java

--------------------
Local command detected, running in local mode
Process finished with exit code 0
```

**Comment by OiAnthony** [comment]
Multiple file editing combined with Chat Panel might be a good idea.
