### ISSUE TITLE
Bug: Does not support JetBrains ^241

### ISSUE THREAD

**Issue by OiAnthony** [phodal/shire#61]
Does not support JetBrains ^241

Perhaps we can limit the supported versions in the plugin.xml

**Comment by phodal** [comment]
It should be supported. 

<img width="1410" alt="image" src="https://github.com/user-attachments/assets/78ff0e10-39f3-437c-acef-3cb468da0d14">

**Comment by OiAnthony** [comment]
😆LOL, my mistake, I thought there would be default actions after installation. Turns out, actions only work after configuring according to the configuration documentation.

@phodal Thank you for your reply.
