### ISSUE TITLE
[Feature request] Support global configuration: ~/.shire/config.json

### ISSUE THREAD

**Issue by OiAnthony** [phodal/shire#70]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support global configuration: `~/.shire/config.json`

Features:
1. IDE-> Settings -> Tools-> Shire, you can open `~/.shire/config.json` to edit to edit
2. Chat Panel can open `~/.shire/config.json` to edit. Related: https://github.com/phodal/shire/issues/68
3. `~/.shire/config.json` support json schema, support grammar prompts, for example: `{"$schema": "https://shire.run/schema.json" "}`
4. When starting the plug-in, there is no `~/.shire/config.json` file automatically creates automatically
5. Global Configuration can configure Model Provider

**Describe Alternatives You've Considered**
Reference: https://docs.Continue.dev/setup/configuration

**Additional context**

**Comment by phodal** [comment]
#78
