### ISSUE TITLE
[Feature request] fast apply suggested code

### ISSUE THREAD

**Issue by OiAnthony** [phodal/shire#71]
**Is your feature request related to a problem? Please describe.**
https://github.com/phodal/shire/issues/68

**Describe the solution you'd like**
Fast apply suggested codes when suggested by the Chat panel.
The model and prompt used by Fast apply can be configured in `~/.shire/config.json`
![image](https://github.com/user-attachments/assets/921968bd-3b9d-458a-be4f-acbb062bba97)

**Describe alternatives you've considered**
Cursor fast apply implementation:
https://www.cursor.com/blog/instant-apply

avante.nvim fast apply implementation：
https://github.com/yetone/avante.nvim/blob/main/lua/avante/llm.lua
Rebuke LLM strictly generate suggested code block without deletion and starting line number and ending line number
Replace the specified code block (start line-end line) with the suggested code block when applying

**Additional context**

**Comment by phodal** [comment]
#68

**Comment by LeoLiuYan** [comment]
This is exciting to see this feature implemented in shire.

@phodal @OiAnthony

**Comment by phodal** [comment]
Not need for current Design princinple
