### ISSUE TITLE
cat 命令失效问题

### ISSUE THREAD

**Issue by ditunes** [phodal/shire#83]
```shire
---
name: "类图分析"
variables:
  "controllers": /.*.java/ { find("Controller") | grep("src/main/java/.*")  | cat }
  "outputFile": /any/ { print("name.adl") }
onStreamingEnd: { parseCode | saveFile($outputFile) }
---


请将下列信息原样输出，不要添加任何其他描述信息：

$controllers
```

cat 无法将识别到的controller内容读取出来，而会把所有的java文件内容读取出来

**Comment by phodal** [comment]
估计不是 cat 的问题，我再看看

不过你这个场景可以考虑直接先改为：

```shire
---
name: "类图分析"
variables:
  "controllers": /.*Controller.java/ { cat }
  "outputFile": /any/ { print("name.adl") }
onStreamingEnd: { parseCode | saveFile($outputFile) }
---


请将下列信息原样输出，不要添加任何其他描述信息：

$controllers
```

**Comment by ditunes** [comment]
> 估计不是 cat 的问题，我再看看
> 
> 不过你这个场景可以考虑直接先改为：
> 
> ```
> ---
> name: "类图分析"
> variables:
>   "controllers": /.*Controller.java/ { cat }
> onStreamingEnd: { parseCode | saveFile("name.adl") }
> ---
> 
> 
> 请将下列信息原样输出，不要添加任何其他描述信息：
> 
> $controllers
> ```

可以先试试，但是我需要的是 更灵活匹配工具，否则prompt大概率要爆。

**Comment by phodal** [comment]
修复了， 原来的 `cat` 的参数取的是输入的 input 而不是 lastResult，所以出错了。

**Comment by ditunes** [comment]
---
name: "类图分析"
variables:
  "output": "name.adl"
  "con": /.*.java/ { print | head(10)}
  "controllers": /.*.java/ { find("Controller") | grep("src/main/java/.*") | head(1)  | cat   }
  "outputFile": /any/ { print("name.adl") }
onStreamingEnd: { parseCode | saveFile($outputFile) }

---


下面是你要执行转换的数据：
$controllers

**Comment by phodal** [comment]
修好了，可以从 action  中下载最新的
