### ISSUE TITLE
IDEA 插件 shire llm配置无法修改

### ISSUE THREAD

**Issue by ditunes** [phodal/shire#85]
<img width="717" alt="image" src="https://github.com/user-attachments/assets/c8068f2a-9f11-40fc-b1d2-32b21ed1eacc">

大模型配置也存在bug，我之前配置了moonshot模型之后，然后想改为本地代理，结果似乎修改不了了，后续代码一直使用moonshot模型在运行，包括test llm都是走的moonshot

**Comment by phodal** [comment]
上次添加动态先找模型的时候留下来的 bug：https://shire.phodal.com/shire/shire-env.html

我更新了新代码上去，改为每次获取
